### ISSUE TITLE
Erro not 'str'

### ISSUE THREAD

**Issue by andreicesmegi** [andreicesmegi/consulta_desec_python#1]
Traceback (most recent call last):
  File "consultanza.py", line 8, in <module>
    s.send (sys.argv[1]+"\r\n")
TypeError: a bytes-like object is required, not 'str'

Olá meus caros, eu não consigo entender onde poder estar o erro no código. Fiz exatamente como o Ricardo mostrou no curso. Tentei um monte de coisas aqui, mas, como sou novato em codificar, não progredi.

**Comment by rf-peixoto** [comment]
Para transmissão de dados utilizando sockets, você precisa converter strings em objetos de bytes, como diz o erro. Para isso, use a função encode(), nativa de strings:

`sys.argv[1].encode()`

Para reconverter em string, utilize decode().
